"""
Compile the portal's JSX into one plain-JavaScript bundle, and vendor React.

WHY THIS EXISTS. The portal was authored the way a design prototype is: React
development builds plus @babel/standalone, transpiling nine JSX files in the
visitor's browser on every single load. That is ~2.5 MB of JavaScript and a
visible pause before anything paints -- fine while designing, wrong for a page
whose whole point is to look like a production service.

This turns it into what it is pretending to be:

    docs/vendor/react.js, react-dom.js   production builds, served same-origin
    docs/portal.bundle.js                every source file, precompiled

leaving the .jsx files as the source of truth. No Babel ships to the browser.

NO NODE ON THIS MACHINE, so the compiler runs where one is guaranteed to
exist: inside Chromium, via Playwright, using the same @babel/standalone the
prototype used to load at runtime. The build has no npm dependency at all.

EACH MODULE IS WRAPPED IN AN IIFE. Concatenating the files as-is would not
even parse: `const { useState } = React` appears at the top of six of them, and
top-level `const` in classic scripts shares one global lexical scope, so the
second declaration is a redeclaration error. Every file already publishes its
public names with `Object.assign(window, {...})` at the bottom, so private
scope per module costs nothing and is what the sources already assume.

ORDER MATTERS and is fixed below: data before the components that read it,
primitives before the screens that use them, app last because it mounts.

Run:
    python scripts/build_portal.py
    python scripts/build_portal.py --check     # verify the bundle is current
"""

from __future__ import annotations

import argparse
import hashlib
import sys
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DOCS = ROOT / "docs"
BUNDLE = DOCS / "portal.bundle.js"
VENDOR = DOCS / "vendor"

BABEL_CDN = "https://unpkg.com/@babel/standalone@7.29.0/babel.min.js"

#: Load order. Plain .js passes through uncompiled; .jsx goes through Babel.
SOURCES = [
    "crm/data.js",            # window.CRM — everything else reads it
    "tweaks-panel.jsx",       # useTweaks + the panel shell
    "ios-frame.jsx",          # IOSDevice, for the mobile view
    "crm/ui.jsx",             # charts and primitives
    "crm/screen-overview.jsx",
    "crm/screen-clients.jsx",
    "crm/screen-analytics.jsx",
    "crm/screen-data.jsx",
    "crm/screen-reports.jsx",
    "crm/screen-auth.jsx",
    "crm/app.jsx",            # mounts — must be last
]

#: React itself. Vendored rather than pulled from a CDN: same-origin means no
#: extra DNS + TLS handshake before the page can run, the site keeps working if
#: unpkg is slow or blocked, and there is no third-party request to trust.
VENDOR_FILES = {
    "react.js": "https://unpkg.com/react@18.3.1/umd/react.production.min.js",
    "react-dom.js": "https://unpkg.com/react-dom@18.3.1/umd/react-dom.production.min.js",
}


def fetch(url: str) -> bytes:
    req = urllib.request.Request(url, headers={"User-Agent": "build_portal"})
    with urllib.request.urlopen(req, timeout=60) as r:
        return r.read()


def vendor_react(force: bool = False) -> list[str]:
    VENDOR.mkdir(parents=True, exist_ok=True)
    notes = []
    for name, url in VENDOR_FILES.items():
        dest = VENDOR / name
        if dest.exists() and not force:
            notes.append(f"  {name:<14} kept   {dest.stat().st_size / 1024:6.1f} KB")
            continue
        data = fetch(url)
        dest.write_bytes(data)
        digest = hashlib.sha256(data).hexdigest()[:12]
        notes.append(f"  {name:<14} pulled {len(data) / 1024:6.1f} KB  sha256:{digest}")
    return notes


def compile_sources() -> tuple[str, list[tuple[str, int, int]]]:
    """Run every source through Babel inside Chromium. Returns the bundle."""
    from playwright.sync_api import sync_playwright

    babel = fetch(BABEL_CDN).decode("utf-8")

    parts = ["/* CRM Analytics — portal bundle. GENERATED by scripts/build_portal.py.\n"
             "   Do not edit: change the .jsx sources and rebuild. */\n"
             '"use strict";\n']
    stats: list[tuple[str, int, int]] = []

    with sync_playwright() as p:
        browser = p.chromium.launch(headless=True)
        page = browser.new_page()
        page.set_content("<!doctype html><meta charset=utf-8><title>build</title>")
        page.add_script_tag(content=babel)

        for rel in SOURCES:
            src_path = DOCS / rel
            if not src_path.exists():
                browser.close()
                raise SystemExit(f"Missing source: {src_path}")
            src = src_path.read_text(encoding="utf-8")

            if src_path.suffix == ".jsx":
                out = page.evaluate(
                    """(code) => {
                        try {
                            return { ok: true, code: Babel.transform(code, {
                                presets: [['react', { runtime: 'classic' }]],
                                sourceType: 'script',
                                compact: false,
                            }).code };
                        } catch (e) { return { ok: false, error: String(e) }; }
                    }""",
                    src,
                )
                if not out["ok"]:
                    browser.close()
                    raise SystemExit(f"Babel failed on {rel}:\n{out['error']}")
                compiled = out["code"]
            else:
                compiled = src

            # One private scope per module — see the note at the top.
            parts.append(
                f"\n/* ---- {rel} ---- */\n(function () {{\n{compiled}\n}})();\n")
            stats.append((rel, len(src), len(compiled)))

        browser.close()

    return "".join(parts), stats


def build(check: bool = False) -> int:
    bundle, stats = compile_sources()

    if check:
        current = BUNDLE.read_text(encoding="utf-8") if BUNDLE.exists() else ""
        if current == bundle:
            print("portal.bundle.js is up to date.")
            return 0
        print("portal.bundle.js is STALE — run: python scripts/build_portal.py")
        return 1

    notes = vendor_react()
    BUNDLE.write_text(bundle, encoding="utf-8")

    print("Vendored React:")
    for n in notes:
        print(n)
    print("\nCompiled:")
    for rel, a, b in stats:
        print(f"  {rel:<28} {a / 1024:7.1f} KB -> {b / 1024:7.1f} KB")

    total = len(bundle.encode("utf-8"))
    vendor_total = sum((VENDOR / n).stat().st_size for n in VENDOR_FILES)
    print(f"\n  {'portal.bundle.js':<28} {total / 1024:7.1f} KB")
    print(f"  {'vendor (react + react-dom)':<28} {vendor_total / 1024:7.1f} KB")
    print(f"  {'TOTAL JS ON THE WIRE':<28} {(total + vendor_total) / 1024:7.1f} KB "
          "(uncompressed; Pages serves it gzipped)")
    return 0


def main() -> None:
    ap = argparse.ArgumentParser(description="Build the portal bundle.")
    ap.add_argument("--check", action="store_true",
                    help="exit non-zero if the committed bundle is stale")
    args = ap.parse_args()
    sys.exit(build(check=args.check))


if __name__ == "__main__":
    main()
